repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.4.0
   hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: forbid-new-submodules
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: check-added-large-files
      args: ['--maxkb=100']
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.0.283
   hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
 - repo: https://github.com/pycqa/isort
   rev: 5.12.0
   hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
 - repo: https://github.com/asottile/pyupgrade
   rev: v3.7.0
   hooks:
    - id: pyupgrade
      args: ['--py39-plus', '--keep-runtime-typing']
 - repo: https://github.com/myint/autoflake
   rev: 'v2.1.1'
   hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports']
 - repo: https://github.com/ambv/black
   rev: 23.3.0
   hooks:
    - id: black
      language_version: python3
 - repo: https://github.com/asottile/blacken-docs
   rev: 1.14.0
   hooks:
    - id: blacken-docs
      additional_dependencies: [black==23.3.0]
