[tool.poetry]
name = "guyhoozdis"
version = "0.1.0"
description = ""
authors = ["Scott Sullivan <scott.sullivan@deepcellbio.com>"]
readme = "README.md"
packages = [{include = "guyhoozdis", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
